file_format: "1"
id: slabboard
name: SlabBoard
type: shield
url: https://github.com/MasonBarney/lunar-zmk
requires: [pro_micro]
exposes: [nice_view_header]
features:
  - keys
  - encoder
  - display
siblings:
  - slabboard_left
  - slabboard_right
